import {
  Activity,
  BookOpen,
  Code,
  Cpu,
  Database,
  Globe,
  Layers,
  Terminal,
} from 'lucide-react'
import { Resource } from './types'

export const RESOURCES: Resource[] = [
  {
    id: '1',
    title: 'SQL Database Guide',
    description: 'Interactive SQL tutorial with live query editor and practical examples.',
    tags: ['Database', 'SQL'],
    icon: Database,
    accent: 'text-[#a8fbd3]',
  },
  {
    id: '2',
    title: 'Software Engineering',
    description: 'Comprehensive guide to software development methodologies and best practices.',
    tags: ['Software', 'Theory'],
    icon: Code,
    accent: 'text-[#4fb7b3]',
  },
  {
    id: '3',
    title: 'Computer Hardware',
    description: 'Essential guide to components, architecture, and how everything works together.',
    tags: ['Hardware', 'Theory'],
    icon: Cpu,
    accent: 'text-[#637ab9]',
  },
  {
    id: '4',
    title: 'Data Processing Modes',
    description: 'Understand batch, online, distributed, and parallel processing strategies.',
    tags: ['Theory', 'Processing'],
    icon: Layers,
    accent: 'text-[#a8fbd3]',
  },
  {
    id: '5',
    title: 'DSE ICT Exam Prep',
    description: 'Practice questions, study tips, and comprehensive exam preparation resources.',
    tags: ['Exam', 'Practice'],
    icon: BookOpen,
    accent: 'text-fuchsia-400',
  },
  {
    id: '6',
    title: 'HTML Learning Tool',
    description: 'Interactive HTML editor with live preview and comprehensive web development guide.',
    tags: ['Web', 'HTML', 'Interactive'],
    icon: Globe,
    accent: 'text-[#4fb7b3]',
  },
  {
    id: '7',
    title: 'Python Algorithm Visualizer',
    description: 'Interactive visualizations with step-by-step explanations for classic algorithms.',
    tags: ['Algorithms', 'Visualization'],
    icon: Activity,
    accent: 'text-[#637ab9]',
  },
  {
    id: '8',
    title: 'JavaScript Interactive Course',
    description: 'Step-by-step interactive JavaScript lessons complete with progress tracking.',
    tags: ['JavaScript', 'Visualization'],
    icon: Terminal,
    accent: 'text-[#a8fbd3]',
  },
]

export const FILTERS = [
  'All',
  'Database',
  'SQL',
  'Software',
  'Theory',
  'Hardware',
  'Processing',
  'Exam',
  'Practice',
  'Web',
  'HTML',
  'Interactive',
  'Algorithms',
  'Visualization',
  'JavaScript',
]
